{{/*
 Licensed to the Apache Software Foundation (ASF) under one
 or more contributor license agreements.  See the NOTICE file
 distributed with this work for additional information
 regarding copyright ownership.  The ASF licenses this file
 to you under the Apache License, Version 2.0 (the
 "License"); you may not use this file except in compliance
 with the License.  You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing,
 software distributed under the License is distributed on an
 "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 KIND, either express or implied.  See the License for the
 specific language governing permissions and limitations
 under the License.
*/}}

# We will create these secrets (if necessary) _even if_ we aren't
# currently using CeleryExecutor, so updating the executor later can deploy
# them when they are needed.
# We will always deploy them defensively to make the executor update path actually work.

################################
## Airflow Redis Password Secret
#################################
{{- $random_redis_password := randAlphaNum 10 }}
{{- $redis_password_secret_name := include "redis_password_secret" . }}
{{- $redis_password_secret := lookup "v1" "Secret" .Release.Namespace $redis_password_secret_name }}
{{- $redis_password := default $random_redis_password .Values.redis.password }}
{{- if and $redis_password_secret (hasKey $redis_password_secret.data "password") }}
{{- $redis_password = index $redis_password_secret.data "password" | b64dec }}
{{- end }}
{{- if and .Values.redis.enabled (not .Values.redis.passwordSecretName) }}
# If passwordSecretName is not set, we will either use the set password, or use the generated one
apiVersion: v1
kind: Secret
metadata:
  name: {{ $redis_password_secret_name }}
  labels:
    tier: airflow
    component: redis
    release: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
    {{- with .Values.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.redis.passwordSecretAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{- if and $redis_password_secret (hasKey $redis_password_secret.data "password") }}
  password: {{ index $redis_password_secret.data "password" | quote }}
  {{- else }}
  password: {{ $redis_password | b64enc | quote }}
  {{- end }}
---
{{- end }}
{{- if not .Values.data.brokerUrlSecretName }}
{{- $redis_broker_url_secret_name := include "airflow_broker_url_secret" . }}
{{- $redis_broker_url_secret := lookup "v1" "Secret" .Release.Namespace $redis_broker_url_secret_name }}
##################################
## Airflow Redis Connection Secret
##################################
apiVersion: v1
kind: Secret
metadata:
  name: {{ $redis_broker_url_secret_name }}
  labels:
    tier: airflow
    component: redis
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}
    heritage: {{ .Release.Service }}
    {{- with .Values.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.data.brokerUrlSecretAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{- if and $redis_broker_url_secret (hasKey $redis_broker_url_secret.data "connection") }}
  connection: {{ index $redis_broker_url_secret.data "connection" | quote }}
  {{- else if .Values.redis.enabled }}
  connection: {{ urlJoin (dict "scheme" "redis" "userinfo" (printf ":%s" ($redis_password | urlquery)) "host" (printf "%s-redis:6379" (include "airflow.fullname" .) ) "path" "/0") | b64enc | quote }}
  {{- else }}
  connection: {{ (printf "%s" .Values.data.brokerUrl) | b64enc | quote }}
  {{- end }}
{{- end }}
